name: XML-Lint

on: [push]

jobs:
  xml-linters:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: add xml problem matcher
      uses: korelstar/xmllint-problem-matcher@v1

    - name: Lint example/*orthoxml
      uses: ChristophWurst/xmllint-action@v1
      with:
        xml-file: ./examples/*orthoxml
        xml-schema-file: ./orthoxml.xsd
